/COMANDOS UTILIZADOS PARA CRIAÇÃO DO BANCO/

CREATE DATABASE ESCOLA_TESTE

USE ESCOLA_TESTE

CREATE TABLE ESCOLA (
	ID_ESCOLA INT NOT NULL IDENTITY,
	NOME_ESCOLA VARCHAR(60) NOT NULL,
	PRIMARY KEY (ID_ESCOLA)
	)

CREATE TABLE TURMA (
	ID_TURMA INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_TURMA VARCHAR(40) NOT NULL,
	SALA_TURMA VARCHAR(15) NOT NULL,
	ID_ESCOLA INT NOT NULL
	CONSTRAINT FK_TURMA_ESCOLA FOREIGN KEY (ID_ESCOLA) REFERENCES ESCOLA(ID_ESCOLA)
)

CREATE TABLE ALUNO (
	ID_ALUNO INT NOT NULL PRIMARY KEY IDENTITY,
	NOME_ALUNO VARCHAR(60) NOT NULL,
	IDADE_ALUNO INT NOT NULL,
	ID_TURMA INT NOT NULL,
	CONSTRAINT FK_ALUNO_TURMA FOREIGN KEY (ID_TURMA) REFERENCES TURMA(ID_TURMA)
)

/INSERINDO AS ESCOLAS/
INSERT INTO ESCOLA (NOME_ESCOLA) VALUES ('PEDRO ALVARES CABRAL')
INSERT INTO ESCOLA (NOME_ESCOLA) VALUES ('JARDIM TIRADENTES')
SELECT * FROM ESCOLA

/INSERINDO AS TURMAS DA ESCOLA 1 - PEDRO ALVARES CABRAL/
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('PRIMEIRO ANO', '1A', 1)
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('SEGUNDO ANO', '2A', 1)
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('TERCEIRO ANO', '3A', 1)

/INSERINDO AS TURMAS DA ESCOLA 2 - JARDIM TIRADENTES/
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('QUINTA SÉRIE', '5S', 2)
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('SEXTA SÉRIE', '6S', 2)
INSERT INTO TURMA (NOME_TURMA, SALA_TURMA, ID_ESCOLA) VALUES ('SÉTIMA SÉRIE', '7S', 2)
SELECT * FROM TURMA

/INSERINDO OS ALUNOS NA TURMA/
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('JOAO BENTO', 6,1)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('MARIA SILVA', 6,1)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('RICARDO PENHA', 7,1)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('JOANA SOUZA', 8,2)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('MARIO GOMES', 7,2)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('SORAYA MARIA', 7,2)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('LUIZ INACIO', 8,3)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('FERNANDO DA SILVA', 9,3)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('MATHEUS ROSA', 8,3)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('JONAS SOUZA', 10,4)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('VANDERLEI CORDEIRO', 11,4)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('HUGO VIDAL', 10,4)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('LUCIANA DA SILVA', 11,5)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('JOÃO PEDRO', 11,5)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('JOSE BATISTA', 11,5)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('GABRIEL TERRA', 12,6)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('FERNANDA PEREIRA', 12,6)
INSERT INTO ALUNO (NOME_ALUNO, IDADE_ALUNO, ID_TURMA) VALUES ('LIDIANE GOMES', 12,6)
SELECT * FROM ALUNO



SELECT * FROM ESCOLA
SELECT * FROM TURMA
SELECT * FROM ALUNO